# Use the official Node.js image
FROM nginx:1.23.2-alpine

LABEL MAINTAINER = Si Rayen

COPY nginx.conf /etc/nginx/nginx.conf

COPY Dailymanagementsystem/dists/dailymanagementsystem /usr/share/nginx/html

EXPOSE 8888

